source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'Exchange' do

pod 'SnapKit'
pod 'Then'
pod 'Moya'
pod 'HandyJSON'
pod 'Kingfisher'
pod 'Reusable'
pod 'LLCycleScrollView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'UINavigation-SXFixSpace'

end
